services:
  - type: web
    name: pedido-lembrancinha-poc
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./docker/app/Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEED
        value: "false"
      - key: APP_URL
        sync: false
      - key: SERVER_ACTIONS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_FORCE_PATH_STYLE
        value: "false"
